### ISSUE TITLE
service config hangs under dokku 0.5,1, 0.5.3, 0.5.5 (vagrant)

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku-rabbitmq#34] opened 2016-04-18 19:01 UTC
```
vagrant@dokku:~$ dokku rabbitmq:create financial-platform
-----> Starting container
       Waiting for container to be ready
```

It hangs forever. But if you control-C...

```
vagrant@dokku:~$ dokku rabbitmq:create financial-platform
-----> Starting container
       Waiting for container to be ready
^C=====> RabbitMQ container created: financial-platform
^CAccess denied
```

Unfortunately this totally hangs my Paver scripts, I can't count on a human sending control-C :-(

Any idea?

**Comment by sglebs** [comment] 2016-04-18 19:06
It keeps happening, even after a destroy:

```
vagrant@dokku:~$ dokku rabbitmq:destroy financial-platform
 !     WARNING: Potentially Destructive Action
 !     This command will destroy financial-platform RabbitMQ service.
 !     To proceed, type "financial-platform"

> financial-platform
-----> Deleting financial-platform
-----> Stopping container
=====> Container stopped
       Removing container
       Removing data
=====> RabbitMQ container deleted: financial-platform
vagrant@dokku:~$ dokku rabbitmq:create financial-platform
-----> Starting container
       Waiting for container to be ready
^C=====> RabbitMQ container created: financial-platform
       DSN: amqp://financial-platform:670b6514959a6cba18ff4cad167275e2@dokku-rabbitmq-financial-platform:5672/financial-platform
vagrant@dokku:~$ 
```

**Comment by josegonzalez** [comment] 2016-04-18 19:19
Under rabbitmq 0.5.5? We don't support that.

**Comment by sglebs** [comment] 2016-04-18 20:29
I fixed the ticket title to clarify.

**Comment by josegonzalez** [comment] 2016-05-04 04:54
Duplicate of #30.

**Closed by josegonzalez** 2016-05-04 04:54 UTC
